#!/usr/bin/env ruby

require 'rubygems'
require 'trollop'
require './lib/include.rb'

opts = Trollop::options do
  opt :config_file, "Configuration file", :type => :string
end

if !opts[:config_file]
  puts "You must specify a backup configuration file. Use the --config=FILE option."
  exit 1
end

if !File.exists?(opts[:config_file])
  puts "Config file doesn't exists"
  exit 2
end

ext = File.extname(opts[:config_file])
case ext
when '.rb' then
  require './'+opts[:config_file]
when '.yml' then
  #TODO: add yml processing here.
else
  puts "Unknown file extension "+ ext
  exit 1
end

include Config

TMP_FOLDER = '/tmp'
Backuper.new(CONFIG).run
