#!/usr/bin/env ruby

require './lib/include.rb'
require './sync_config.rb'

include SyncConfig

backuper = Backuper.new(CONFIG)

if ARGV.include? '--sync-remote-config'
	puts "Synchronizing remote config..."
	backuper.sync_remote_config
	exit 0
end

backuper.run

