class Backuper
  def initialize(config)
    @backups = config[:backups]
    @rotations = config[:rotations]
    @remote_target = config[:remote_target]
    @remote_port = config[:remote_port]
    @local_target = config[:local_target]
    @mail_target = config[:mail_target]
    @date_format = config[:date_format] ? config[:date_format] : '%Y_%m_%d'
    @stop_on_fail = config[:stop_on_fail] === nil ? false : config[:stop_on_fail]
    @attachment_extension = config[:attachment_extension]

    @backup_classes = {
      :folder => FolderBackup,
      :mongo => MongoDBBackup,
      :mysql => MySQLBackup
    }
  end

  def run
    @tmp_folder = File.join(TMP_FOLDER, random_string)
    check_folders

    @backups.each do |backup_config|
      type = backup_config[:type].intern
      backup_obj = @backup_classes[type].new backup_config
      backup_obj.set_config tmp_folder: @tmp_folder, local_target: @local_target, remote_target: @remote_target, mail_target: @mail_target
      begin
        backup_obj.run
      rescue Exception => e
        puts e
        puts "Canceling backup #{backup_obj.name}"
        
        if @stop_on_fail
          puts "Canceling whole backup"
          raise e
        end
      end
    end

    # some mail servers doesn't accept .tar.gz files, so the user can use another extension. 
    extension = @attachment_extension ? @attachment_extension : '.tar.gz'

    filename = File.join(TMP_FOLDER, Time.now.strftime(@date_format)+extension)
    puts "Filename: #{filename}"
    system("tar -cf #{filename} #{@tmp_folder}")
    FileUtils.rm_rf @tmp_folder

    if @local_target 
      result = FileUtils.mv filename, @local_target
      puts "File #{filename} moved successfully to #{@local_target}"
      rotate_files
    end

    if @remote_target
      remote_port = @remote_port ? @remote_port : 22
      command = "scp -P #{@remote_port} #{filename} #{@remote_target}"
      puts "Executing... "+command
      system(command)
    end

    if @mail_target
      require 'mail'

      mail_target = @mail_target
      mail_target = 'ham1988@gmail.com'
      mail = Mail.new do
        from    'backup@backuper.com'
        to       mail_target
        subject 'Backup available'
        body    "This is an automatic mail generated by backuper."        
        add_file filename
      end

      mail.delivery_method :sendmail, :arguments => '-i'
      mail.deliver
    end

    # deleting temp data
    if File.exists?(filename)
      File.unlink filename
    end
  end

  def check_config
    # I'll probably should implement something here, right?
  end

  def rotate_files
    if !@rotations
      return
    end

    puts "Rotating files"

    files = Dir[File.join(@local_target, '**', '*')].sort
    for i in (@rotations..(files.length-1)) do
      puts "Deleting "+files[i]
      File.delete(files[i])
    end
  end

  def check_folders
    Dir.mkdir @tmp_folder
    if @local_target and !Dir.exists? @local_target
      Dir.mkdir @local_target
    end
  end

  private
  def random_string
    (0...20).map{ ('a'..'z').to_a[rand(26)] }.join
  end
end

# monkey patch
#module Mail
#  class ::Sendmail
#    def initialize(values) 
#      puts values
#      throw "sdfsd"
#      self.settings = { :location => '/usr/sbin/sendmail', :arguments => '-i'}.merge(values)
#    end
# end
#end
